#!/bin/sh
# gen-ksyms.sh — emit a C kernel symbol table from a linked ELF, for in-kernel
# symbolized backtraces (panic + stackshot).  Reads function symbols in the
# higher-half text range, sorted by address, and writes build/ksyms.c defining
# the strong arrays that override the weak fallbacks in kernel/core/ksym.c.
#
# Single-pass-safe: the kernel's .text is laid out before .rodata (linker.ld),
# so embedding this (const → .rodata) does not shift any function address —
# the addresses captured here stay valid in the relink.
#
# Usage: sh tools/gen-ksyms.sh <kernel.elf> > build/ksyms.c
set -e
ELF="$1"
NM="${NM:-nm}"

"$NM" -n "$ELF" | awk '
    BEGIN { n = 0 }   # without this, addr[n] on the first match keys addr[""]
    # nm -n output: "<addr> <type> <name>", sorted ascending by address.
    # Keep text/code symbols (t,T local/global; w,W weak) in the kernel
    # higher-half range, with a plain-identifier name.  Anchored to the whole
    # line so blank-address lines (undefined weak symbols) cannot slip in.
    /^ffffffff[0-9a-f]+ [tTwW] [A-Za-z_][A-Za-z0-9_.]*$/ {
        addr[n] = $1; name[n] = $3; n++
    }
    END {
        print "/* GENERATED by tools/gen-ksyms.sh — do not edit. */"
        print "#include <stdint.h>"
        printf "const uint32_t ksym_count = %d;\n", n
        print "const uint64_t ksym_addrs[] = {"
        for (i = 0; i < n; i++) printf "  0x%sUL,\n", addr[i]
        print "};"
        print "const uint32_t ksym_name_off[] = {"
        off = 0
        for (i = 0; i < n; i++) { printf "  %d,\n", off; off += length(name[i]) + 1 }
        print "};"
        # One concatenated string literal: "n1\0" "n2\0" ... — adjacent literals
        # join, each contributes name+explicit-NUL, so name_off (cumulative
        # len+1) indexes correctly into ksym_names.
        print "const char ksym_names[] ="
        for (i = 0; i < n; i++) printf "  \"%s\\0\"\n", name[i]
        print ";"
    }'
