#!/bin/sh
# gen-ksyms.sh — emit a C kernel symbol table from a linked ELF, for in-kernel
# symbolized backtraces (panic + stackshot).  Reads function symbols in the
# higher-half text range, sorted by address, and writes build/ksyms.c defining
# the strong arrays that override the weak fallbacks in kernel/core/ksym.c.
#
# Single-pass-safe: the kernel's .text is laid out before .rodata (linker.ld),
# so embedding this (const → .rodata) does not shift any function address —
# the addresses captured here stay valid in the relink.
#
# POSIX-sh + grep only (NO awk): awk isn't in the self-hosting toolchain rootfs,
# and this must run under stsh when the kernel is built ON Aegis. Names are laid
# out NUL-separated (no offset table) — kernel/core/ksym.c walks to the i-th name
# — so no per-name length arithmetic is needed.
#
# Usage: $(SHELL) tools/gen-ksyms.sh <kernel.elf> > build/ksyms.c
set -e
ELF="$1"
NM="${NM:-nm}"
TMP="$ELF.ksymtmp"

# nm -n: "<addr> <type> <name>", sorted ascending. Keep text/code symbols
# (t,T,w,W) in the higher-half range with a plain-identifier name; the anchored
# pattern drops blank-address (undefined weak) lines.
"$NM" -n "$ELF" | grep -E '^ffffffff[0-9a-f]+ [tTwW] [A-Za-z_][A-Za-z0-9_.]*$' > "$TMP" || true

echo "/* GENERATED by tools/gen-ksyms.sh — do not edit. */"
echo "#include <stdint.h>"

echo "const uint64_t ksym_addrs[] = {"
cat "$TMP" | while read addr type name; do printf '  0x%sUL,\n' "$addr"; done
echo "};"

# One concatenated string literal: "n1\0" "n2\0" ... — adjacent literals join,
# each contributes name+explicit-NUL. ksym_lookup walks NULs to index it.
echo "const char ksym_names[] ="
cat "$TMP" | while read addr type name; do printf '  "%s\\0"\n' "$name"; done
echo ";"

# Count last: C allows the definition after the arrays it describes.
n=$(wc -l < "$TMP")
printf 'const uint32_t ksym_count = %d;\n' "$n"

rm -f "$TMP"
